# Generated by Django 4.2.2 on 2023-06-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SANAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias_name", models.CharField(max_length=200)),
                ("WWPN", models.CharField(max_length=23)),
                ("use", models.CharField(max_length=200)),
            ],
        ),
    ]
