# Generated by Django 4.2.9 on 2024-04-02 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wwpn', models.CharField(max_length=23)),
                ('use', models.CharField(blank=True, choices=[('init', 'Initiator'), ('target', 'Target'), ('both', 'Both')], max_length=6, null=True)),
                ('create', models.BooleanField(default=False)),
                ('include_in_zoning', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('zoneset_name', models.CharField(max_length=200)),
                ('vsan', models.IntegerField(blank=True, null=True)),
                ('exists', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='san_app.customer')),
            ],
            options={
                'unique_together': {('customer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('storage_type', models.CharField(choices=[('FlashSystem', 'FlashSystem'), ('DS8000', 'DS8000'), ('Switch', 'Switch')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_type', models.CharField(blank=True, max_length=4, null=True)),
                ('model', models.CharField(blank=True, max_length=3, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_image', models.CharField(blank=True, max_length=7, null=True)),
                ('system_id', models.CharField(blank=True, max_length=16, null=True)),
                ('firmware_level', models.CharField(blank=True, max_length=16, null=True)),
                ('primary_ip', models.CharField(blank=True, max_length=11, null=True)),
                ('secondary_ip', models.CharField(blank=True, max_length=11, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='san_app.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ZoneGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create', models.BooleanField(default=False)),
                ('zone_type', models.CharField(choices=[('smart', 'smart'), ('standard', 'standard')], max_length=100)),
                ('exists', models.BooleanField(default=False)),
                ('aliases', models.ManyToManyField(to='san_app.alias')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_app.fabric')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_app.storage')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create', models.BooleanField(default=False)),
                ('exists', models.BooleanField(default=False)),
                ('zone_type', models.CharField(choices=[('smart', 'smart'), ('standard', 'standard')], max_length=100)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_app.fabric')),
                ('members', models.ManyToManyField(to='san_app.alias')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_ranges', to='san_app.project')),
            ],
        ),
        migrations.AddField(
            model_name='fabric',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='san_app.project'),
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('san_vendor', models.CharField(choices=[('BR', 'Brocade'), ('CI', 'Cisco')], max_length=7)),
                ('cisco_alias', models.CharField(choices=[('device-alias', 'device-alias'), ('fcalias', 'fcalias')], max_length=15)),
                ('cisco_zoning_mode', models.CharField(choices=[('basic', 'basic'), ('enhanced', 'enhanced')], max_length=15)),
                ('zone_ratio', models.CharField(choices=[('one-to-one', 'one-to-one'), ('one-to-many', 'one-to-many'), ('all-to-all', 'all-to-all')], max_length=20)),
                ('zoning_job_name', models.CharField(max_length=40)),
                ('smartzone_prefix', models.CharField(max_length=25)),
                ('alias_max_zones', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='san_app.project')),
            ],
        ),
        migrations.AddField(
            model_name='alias',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='san_app.fabric'),
        ),
        migrations.AddField(
            model_name='alias',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='san_app.storage'),
        ),
        migrations.AlterUniqueTogether(
            name='fabric',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together={('fabric', 'wwpn')},
        ),
    ]
